version: '3'
services:
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
  console:
    build:
      context: ./php/console
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    tty: true
  node:
    image: node
    volumes:
      - ./app:/var/www/html
    tty: true
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123123"
    volumes:
      - db:/var/lib/mysql
      - ./php/mysql/config/my.cnf:/etc//mysql/mysql.conf.d/mysqld.cnf
volumes:
  db:
    driver: local